### ISSUE TITLE
Crash on startup - assertion fails on Mac OS X Lion

### ISSUE THREAD

**Issue by dalegillard** [reborg/pomodori#10]
Process:         Pomodori [748]
Path:            /Users/USER/Downloads/Pomodori.app/Contents/MacOS/Pomodori
Identifier:      Pomodori
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [174]

Date/Time:       2011-07-18 22:12:53.280 +1000
OS Version:      Mac OS X 10.7 (11A511)
Report Version:  9

Interval Since Last Report:          66480 sec
Crashes Since Last Report:           1
Per-App Crashes Since Last Report:   1
Anonymous UUID:                      F6C31CB1-BD61-4F5F-B74B-ED6EB0A505D0

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
objc[748]: garbage collection is ON
Assertion failed: (sel_ignored == sel_registerName("release")), function Init_id, file id.c, line 79.

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib          0x00007fff8770bce2 __pthread_kill + 10
1   libsystem_c.dylib               0x00007fff8aac37d2 pthread_kill + 95
2   libsystem_c.dylib               0x00007fff8aab4a7a abort + 143
3   libsystem_c.dylib               0x00007fff8aae75de __assert_rtn + 146
4   libmacruby.1.9.0.dylib          0x000000010010fff7 Init_id + 3783
5   libmacruby.1.9.0.dylib          0x0000000100054d3e rb_call_inits + 14
6   libmacruby.1.9.0.dylib          0x00000001000408d8 ruby_init + 152
7   libmacruby.1.9.0.dylib          0x000000010017fa84 macruby_main + 292
8                                   0x0000000100000e78 main + 34
9                                   0x0000000100000b34 start + 52

Thread 1:
0   libsystem_kernel.dylib          0x00007fff8770c192 __workq_kernreturn + 10
1   libsystem_c.dylib               0x00007fff8aac3594 _pthread_wqthread + 758
2   libsystem_c.dylib               0x00007fff8aac4b85 start_wqthread + 13

Thread 2:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib          0x00007fff8770c7e6 kevent + 10
1   libdispatch.dylib               0x00007fff8456c60e _dispatch_mgr_invoke + 923
2   libdispatch.dylib               0x00007fff8456b19e _dispatch_mgr_thread + 54

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x0000000000000006  rcx: 0x00007fff5fbffbb8  rdx: 0x0000000000000000
  rdi: 0x0000000000000a07  rsi: 0x0000000000000006  rbp: 0x00007fff5fbffbe0  rsp: 0x00007fff5fbffbb8
   r8: 0x00007fff718d2fb8   r9: 0x000000000000004f  r10: 0x00007fff8770bd0a  r11: 0xffffff80002d8240
  r12: 0x00000001009777ac  r13: 0x0000000100efc000  r14: 0x00007fff718d5960  r15: 0x00000001009775a3
  rip: 0x00007fff8770bce2  rfl: 0x0000000000000246  cr2: 0x0000000100efc000
Logical CPU: 0

Binary Images:
       0x100000000 -        0x100000fff + (??? - 0.6 © ReBorg reborg@reborg.net) <494DF122-748C-331F-A308-59E31FAFA74D> /Users/USER/Downloads/Pomodori.app/Contents/MacOS/Pomodori
       0x100003000 -        0x100afbf37 +libmacruby.1.9.0.dylib (0.5.0 - compatibility 0.5.0) <9EAB53FE-FE2F-308D-8F4B-B6F867658B2F> /Users/USER/Downloads/Pomodori.app/Contents/Frameworks/MacRuby.framework/Versions/0.5/usr/lib/libmacruby.1.9.0.dylib
    0x7fff6475a000 -     0x7fff6478eac7  dyld (195.5 - ???) <4A6E2B28-C7A2-3528-ADB7-4076B9836041> /usr/lib/dyld
    0x7fff80179000 -     0x7fff8017efff  libcache.dylib (47.0.0 - compatibility 1.0.0) <B7757E2E-5A7D-362E-AB71-785FE79E1527> /usr/lib/system/libcache.dylib
    0x7fff8017f000 -     0x7fff80181fff  com.apple.TrustEvaluationAgent (2.0 - 1) <80AFB5D8-5CC4-3A38-83B9-A7DF5820031A> /System/Library/PrivateFrameworks/TrustEvaluationAgent.framework/Versions/A/TrustEvaluationAgent
    0x7fff80698000 -     0x7fff80699fff  liblangid.dylib (??? - ???) <CACBE3C3-2F7B-3EED-B50E-EDB73F473B77> /usr/lib/liblangid.dylib
    0x7fff8069a000 -     0x7fff8069bfff  libsystem_sandbox.dylib (??? - ???) <8D14139B-B671-35F4-9E5A-023B4C523C38> /usr/lib/system/libsystem_sandbox.dylib
    0x7fff81a0a000 -     0x7fff81d23fff  com.apple.CoreServices.CarbonCore (960.13 - 960.13) <398ABDD7-BB95-3C05-96D2-B54243FC4745> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CarbonCore.framework/Versions/A/CarbonCore
    0x7fff81e57000 -     0x7fff81f37fff  com.apple.CoreServices.OSServices (478.25 - 478.25) <CA11FC11-2F93-3C8A-8077-A67F381A3EBE> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices
    0x7fff81fba000 -     0x7fff81fc2fff  libsystem_dnssd.dylib (??? - ???) <7749128E-D0C5-3832-861C-BC9913F774FA> /usr/lib/system/libsystem_dnssd.dylib
    0x7fff82007000 -     0x7fff82019ff7  libz.1.dylib (1.2.5 - compatibility 1.0.0) <30CBEF15-4978-3DED-8629-7109880A19D4> /usr/lib/libz.1.dylib
    0x7fff8279f000 -     0x7fff82821fff  com.apple.Metadata (10.7.0 - 627.9) <F293A9A7-9790-3629-BE81-D19C158C5EA4> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/Metadata.framework/Versions/A/Metadata
    0x7fff83045000 -     0x7fff83074fff  com.apple.DictionaryServices (1.2 - 158) <2CE51CD1-EE3D-3618-9507-E39A09C9BB8D> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/DictionaryServices.framework/Versions/A/DictionaryServices
    0x7fff8321e000 -     0x7fff83230ff7  libbsm.0.dylib (??? - ???) <349BB16F-75FA-363F-8D98-7A9C3FA90A0D> /usr/lib/libbsm.0.dylib
    0x7fff83231000 -     0x7fff8323ffff  com.apple.NetAuth (1.0 - 3.0) <F384FFFD-70F6-3B1C-A886-F5B446E456E7> /System/Library/PrivateFrameworks/NetAuth.framework/Versions/A/NetAuth
    0x7fff83240000 -     0x7fff83242fff  libquarantine.dylib (36.0.0 - compatibility 1.0.0) <4C3BFBC7-E592-3939-B376-1C2E2D7C5389> /usr/lib/system/libquarantine.dylib
    0x7fff833e0000 -     0x7fff83453fff  libstdc++.6.dylib (52.0.0 - compatibility 7.0.0) <6BDD43E4-A4B1-379E-9ED5-8C713653DFF2> /usr/lib/libstdc++.6.dylib
    0x7fff83653000 -     0x7fff83692fff  com.apple.AE (527.6 - 527.6) <6F8DF9EF-3250-3B7F-8841-FCAD8E323954> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/AE.framework/Versions/A/AE
    0x7fff83693000 -     0x7fff83795ff7  libxml2.2.dylib (10.3.0 - compatibility 10.0.0) <D46F371D-6422-31B7-BCE0-D80713069E0E> /usr/lib/libxml2.2.dylib
    0x7fff8382a000 -     0x7fff8383dff7  libCRFSuite.dylib (??? - ???) <034D4DAA-63F0-35E4-BCEF-338DD7A453DD> /usr/lib/libCRFSuite.dylib
    0x7fff838e7000 -     0x7fff838eefff  com.apple.NetFS (4.0 - 4.0) <B9F41443-679A-31AD-B0EB-36557DAF782B> /System/Library/Frameworks/NetFS.framework/Versions/A/NetFS
    0x7fff838ef000 -     0x7fff83989ff7  com.apple.SearchKit (1.4.0 - 1.4.0) <B7573888-BAF6-333D-AB00-C0D2BF88DF0F> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SearchKit.framework/Versions/A/SearchKit
    0x7fff8426d000 -     0x7fff8427bff7  libkxld.dylib (??? - ???) <65BE345D-6618-3D1A-9E2B-255E629646AA> /usr/lib/system/libkxld.dylib
    0x7fff8427f000 -     0x7fff84280fff  libunc.dylib (24.0.0 - compatibility 1.0.0) <C67B3B14-866C-314F-87FF-8025BEC2CAAC> /usr/lib/system/libunc.dylib
    0x7fff84281000 -     0x7fff842c3ff7  libcommonCrypto.dylib (55010.0.0 - compatibility 1.0.0) <A5B9778E-11C3-3F61-B740-1F2114E967FB> /usr/lib/system/libcommonCrypto.dylib
    0x7fff842c4000 -     0x7fff842cafff  com.apple.DiskArbitration (2.4 - 2.4) <5185FEA6-92CA-3CAA-8442-BD71DBC64AFD> /System/Library/Frameworks/DiskArbitration.framework/Versions/A/DiskArbitration
    0x7fff844c9000 -     0x7fff84568fff  com.apple.LaunchServices (480.19 - 480.19) <41ED4C8B-C74B-34EA-A9BF-34DBA5F52307> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices
    0x7fff84569000 -     0x7fff84577fff  libdispatch.dylib (187.5.0 - compatibility 1.0.0) <698F8EFB-7075-3111-94E3-891156C88172> /usr/lib/system/libdispatch.dylib
    0x7fff8465c000 -     0x7fff8465dfff  libDiagnosticMessagesClient.dylib (??? - ???) <3DCF577B-F126-302B-BCE2-4DB9A95B8598> /usr/lib/libDiagnosticMessagesClient.dylib
    0x7fff8465e000 -     0x7fff846c8fff  com.apple.framework.IOKit (2.0 - ???) <F79E7690-EF97-3D04-BA22-177E256803AF> /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit
    0x7fff855f7000 -     0x7fff856dbdef  libobjc.A.dylib (228.0.0 - compatibility 1.0.0) <C5F2392D-B481-3A9D-91BE-3D039FFF4DEC> /usr/lib/libobjc.A.dylib
    0x7fff856dc000 -     0x7fff8583ffff  com.apple.CFNetwork (520.0.13 - 520.0.13) <67E3BB43-2A22-3F5A-964E-391375B24CE0> /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/CFNetwork.framework/Versions/A/CFNetwork
    0x7fff85a6e000 -     0x7fff85a72fff  libmathCommon.A.dylib (2026.0.0 - compatibility 1.0.0) <FF83AFF7-42B2-306E-90AF-D539C51A4542> /usr/lib/system/libmathCommon.A.dylib
    0x7fff85a79000 -     0x7fff85d8bfff  com.apple.Foundation (6.7 - 833.1) <618D7923-3519-3C53-9CBD-CF3C7130CB32> /System/Library/Frameworks/Foundation.framework/Versions/C/Foundation
    0x7fff86628000 -     0x7fff86655fe7  libSystem.B.dylib (159.0.0 - compatibility 1.0.0) <7B4D685D-939C-3ABE-8780-77A1889E0DE9> /usr/lib/libSystem.B.dylib
    0x7fff86772000 -     0x7fff86778fff  libmacho.dylib (800.0.0 - compatibility 1.0.0) <D86F63EC-D2BD-32E0-8955-08B5EAFAD2CC> /usr/lib/system/libmacho.dylib
    0x7fff869a4000 -     0x7fff869c0ff7  com.apple.GenerationalStorage (1.0 - 124) <C0290CA0-A2A0-3280-9442-9D783883D638> /System/Library/PrivateFrameworks/GenerationalStorage.framework/Versions/A/GenerationalStorage
    0x7fff869c7000 -     0x7fff86a15ff7  libauto.dylib (??? - ???) <F0004B88-CA01-37D0-A77F-6651C4EC7D8E> /usr/lib/libauto.dylib
    0x7fff86a16000 -     0x7fff86a1dfff  libcopyfile.dylib (85.1.0 - compatibility 1.0.0) <172B1985-F24A-34E9-8D8B-A2403C9A0399> /usr/lib/system/libcopyfile.dylib
    0x7fff86a1e000 -     0x7fff86a5afff  libsystem_info.dylib (??? - ???) <BC49C624-1DAB-3A37-890F-6EFD46538424> /usr/lib/system/libsystem_info.dylib
    0x7fff86a5b000 -     0x7fff86a61ff7  libunwind.dylib (30.0.0 - compatibility 1.0.0) <1E9C6C8C-CBE8-3F4B-A5B5-E03E3AB53231> /usr/lib/system/libunwind.dylib
    0x7fff8703d000 -     0x7fff87149fef  libcrypto.0.9.8.dylib (0.9.8 - compatibility 0.9.8) <3AD29F8D-E3BC-3F49-A438-2C8AAB71DC99> /usr/lib/libcrypto.0.9.8.dylib
    0x7fff872f9000 -     0x7fff872fafff  libffi.dylib (??? - ???) <DB96CC4B-0D38-3102-80AA-91DDE9AF3886> /usr/lib/libffi.dylib
    0x7fff87699000 -     0x7fff8769aff7  libremovefile.dylib (21.0.0 - compatibility 1.0.0) <C6C49FB7-1892-32E4-86B5-25AD165131AA> /usr/lib/system/libremovefile.dylib
    0x7fff876f5000 -     0x7fff87715fff  libsystem_kernel.dylib (1699.22.73 - compatibility 1.0.0) <69F2F501-72D8-3B3B-8357-F4418B3E1348> /usr/lib/system/libsystem_kernel.dylib
    0x7fff87727000 -     0x7fff8773efff  com.apple.CFOpenDirectory (10.7 - 144) <9709423E-8484-3B26-AAE8-EF58D1B8FB3F> /System/Library/Frameworks/OpenDirectory.framework/Versions/A/Frameworks/CFOpenDirectory.framework/Versions/A/CFOpenDirectory
    0x7fff87b33000 -     0x7fff87b37fff  libdyld.dylib (195.5.0 - compatibility 1.0.0) <F1903B7A-D3FF-3390-909A-B24E09BAD1A5> /usr/lib/system/libdyld.dylib
    0x7fff881a4000 -     0x7fff881c1ff7  libxpc.dylib (77.16.0 - compatibility 1.0.0) <0A4B4775-29A9-30D6-956B-3BE1DBF98090> /usr/lib/system/libxpc.dylib
    0x7fff881c2000 -     0x7fff881c7ff7  libsystem_network.dylib (??? - ???) <4ABCEEF3-A3F9-3E06-9682-CE00F17138B7> /usr/lib/system/libsystem_network.dylib
    0x7fff881d1000 -     0x7fff8821cfff  com.apple.SystemConfiguration (1.11 - 1.11) <0B02FEC4-C36E-32CB-8004-2214B6793AE8> /System/Library/Frameworks/SystemConfiguration.framework/Versions/A/SystemConfiguration
    0x7fff89360000 -     0x7fff89637fff  com.apple.security (7.0 - 55010) <2418B583-D3BD-3BC5-8B07-8289C8A5B43B> /System/Library/Frameworks/Security.framework/Versions/A/Security
    0x7fff8965b000 -     0x7fff89686ff7  libxslt.1.dylib (3.24.0 - compatibility 3.0.0) <8051A3FC-7385-3EA9-9634-78FC616C3E94> /usr/lib/libxslt.1.dylib
    0x7fff89687000 -     0x7fff89889fff  libicucore.A.dylib (46.1.0 - compatibility 1.0.0) <82DCB94B-3819-3CC3-BC16-2AACA7F64F8A> /usr/lib/libicucore.A.dylib
    0x7fff89fac000 -     0x7fff89fadff7  libsystem_blocks.dylib (53.0.0 - compatibility 1.0.0) <8BCA214A-8992-34B2-A8B9-B74DEACA1869> /usr/lib/system/libsystem_blocks.dylib
    0x7fff8a030000 -     0x7fff8a133fff  libsqlite3.dylib (9.6.0 - compatibility 9.0.0) <ED5E84C6-646D-3B70-81D6-7AF957BEB217> /usr/lib/libsqlite3.dylib
    0x7fff8a170000 -     0x7fff8a175fff  libcompiler_rt.dylib (6.0.0 - compatibility 1.0.0) <98ECD5F6-E85C-32A5-98CD-8911230CB66A> /usr/lib/system/libcompiler_rt.dylib
    0x7fff8a176000 -     0x7fff8a17ffff  libnotify.dylib (80.0.0 - compatibility 1.0.0) <BD08553D-8088-38A8-8007-CF5C0B8F0404> /usr/lib/system/libnotify.dylib
    0x7fff8a320000 -     0x7fff8a325fff  libpam.2.dylib (3.0.0 - compatibility 3.0.0) <D952F17B-200A-3A23-B9B2-7C1F7AC19189> /usr/lib/libpam.2.dylib
    0x7fff8a4b1000 -     0x7fff8a684ff7  com.apple.CoreFoundation (6.7 - 635) <57446B22-0778-3E07-9690-96AC705D57E8> /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation
    0x7fff8a793000 -     0x7fff8a794fff  libdnsinfo.dylib (395.6.0 - compatibility 1.0.0) <718A135F-6349-354A-85D5-430B128EFD57> /usr/lib/system/libdnsinfo.dylib
    0x7fff8aa73000 -     0x7fff8ab50fef  libsystem_c.dylib (763.11.0 - compatibility 1.0.0) <1D61CA57-3C6D-30F7-89CB-CC6F0787B1DC> /usr/lib/system/libsystem_c.dylib
    0x7fff8acb0000 -     0x7fff8acb0fff  libkeymgr.dylib (23.0.0 - compatibility 1.0.0) <61EFED6A-A407-301E-B454-CD18314F0075> /usr/lib/system/libkeymgr.dylib
    0x7fff8acb1000 -     0x7fff8acbcff7  libc++abi.dylib (14.0.0 - compatibility 1.0.0) <8FF3D766-D678-36F6-84AC-423C878E6D14> /usr/lib/libc++abi.dylib
    0x7fff8bdf6000 -     0x7fff8be00ff7  liblaunch.dylib (392.18.0 - compatibility 1.0.0) <39EF04F2-7F0C-3435-B785-BF283727FFBD> /usr/lib/system/liblaunch.dylib
    0x7fff8c504000 -     0x7fff8c574fff  com.apple.datadetectorscore (3.0 - 179.3) <AFFBD606-91DE-3F91-8E38-C037D9FBFA8B> /System/Library/PrivateFrameworks/DataDetectorsCore.framework/Versions/A/DataDetectorsCore
    0x7fff8c6cb000 -     0x7fff8c740ff7  libc++.1.dylib (19.0.0 - compatibility 1.0.0) <C0EFFF1B-0FEB-3F99-BE54-506B35B555A9> /usr/lib/libc++.1.dylib
    0x7fff8c75c000 -     0x7fff8c75cfff  com.apple.CoreServices (53 - 53) <5946A0A6-393D-3087-86A0-4FFF6A305CC0> /System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 1
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 876
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=88.4M resident=66.5M(75%) swapped_out_or_unallocated=21.9M(25%)
Writable regions: Total=16.1G written=1784K(0%) resident=1932K(0%) swapped_out=0K(0%) unallocated=16.1G(100%)

REGION TYPE                      VIRTUAL
===========                      =======
MALLOC                            191.6M
MALLOC (reserved)                  15.9G        reserved VM address space (unallocated)
MALLOC guard page                    48K
STACK GUARD                        56.0M
Stack                              9232K
VM_ALLOCATE                         676K
__DATA                             3348K
__LINKEDIT                         50.4M
__TEXT                             38.0M
__UNICODE                           544K
shared memory                        12K
===========                      =======
TOTAL                              16.2G
TOTAL, minus reserved VM space    349.5M

Model: MacBookPro6,2, BootROM MBP61.0057.B0C, 2 processors, Intel Core i5, 2.4 GHz, 8 GB, SMC 1.58f16
Graphics: NVIDIA GeForce GT 330M, NVIDIA GeForce GT 330M, PCIe, 256 MB
Graphics: Intel HD Graphics, Intel HD Graphics, Built-In, 288 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1067 MHz, 0x857F, 0x483634353155363446373036364700000000
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1067 MHz, 0x857F, 0x483634353155363446373036364700000000
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x93), Broadcom BCM43xx 1.0 (5.100.98.75.6)
Bluetooth: Version 2.5.0f17, 2 service, 19 devices, 1 incoming serial ports
Network Service: AirPort, AirPort, en1
Serial ATA Device: TOSHIBA MK5055GSXF, 500.11 GB
Serial ATA Device: MATSHITADVD-R   UJ-898
USB Device: hub_device, 0x0424  (SMSC), 0x2514, 0xfa100000 / 2
USB Device: BRCM2070 Hub, 0x0a5c  (Broadcom Corp.), 0x4500, 0xfa110000 / 5
USB Device: Bluetooth USB Host Controller, apple_vendor_id, 0x8218, 0xfa113000 / 8
USB Device: Apple Internal Keyboard / Trackpad, apple_vendor_id, 0x0236, 0xfa120000 / 4
USB Device: Internal Memory Card Reader, apple_vendor_id, 0x8403, 0xfa130000 / 3
USB Device: hub_device, 0x0424  (SMSC), 0x2514, 0xfd100000 / 2
USB Device: IR Receiver, apple_vendor_id, 0x8242, 0xfd120000 / 4
USB Device: Built-in iSight, apple_vendor_id, 0x8507, 0xfd110000 / 3

**Comment by bcardarella** [comment]
I'm seeing this too. Any chance we can get a fix?

**Comment by reborg** [comment]
Sorry, it took me a while to find the time (and move to Lion). Please go ahead and download http://reborg.github.com/pomodori/resources/pomodori-0.7.zip it should work on Lion. Let me know.

**Comment by bcardarella** [comment]
@rebord awesome! Thank-you very much :)
