### ISSUE TITLE
pomodori does not work on case-sensitive filesystems

### ISSUE THREAD

**Issue by chenmoucheng** [reborg/pomodori#4]
On a case-sensitive filesystem, pomodori gives the following error message:

main.rb:1:in `<main>': framework`foundation' not found (RuntimeError)
        from rb_main.rb:1:in `<main>'

A dtruss trace shows that it tries to load /System/Library/Frameworks/Foundation.framework via lstat64("/System/Library/Frameworks/foundation.framework\0", ...), which fails on a case-sensitive filesystem.  Could you please fix this bug?  Thanks!

**Comment by reborg** [comment]
Looks like I misspelled the case on my case insensitive file system. I fixed this in the 0.6 release: http://reborg.github.com/pomodori/resources/pomodori-0.6.zip but couldn't test it. Please let me know.

**Comment by chenmoucheng** [comment]
Thanks!  However, when I click on the above link, I get "Page does not exist!" :-(

**Comment by reborg** [comment]
Sorry, that was another case problem.

**Comment by chenmoucheng** [comment]
It works!  Thanks! :D
