### ISSUE TITLE
Pomodori 0.4 install problem on Mac OS X 10.5

### ISSUE THREAD

**Issue by redsplat** [reborg/pomodori#5]
Mac OS X 10.5.8, trying to install Pomodori 0.4. 

D/L the zip, unarchive it, drag/drop it to the applications folder, no prob. But every time I try to open it, I get "The application Pomodori quit unexpectedly."

Repeated a number of times, no difference. Tried to reset & relaunch but no dice. Also tried to open it _before_ moving it to Applications folder. Even tried installing Pomodori 0.5 & 0.6 out of desperation :P

Thanks in advance for any help you can offer.

**Comment by reborg** [comment]
Hi,

in http://reborg.github.com/pomodori/resources/pomodori-0.4.zip MacRuby was not embedded, and I think I removed accidentally the instructions about it. Just to be sure, do you have http://www.macruby.org/files/MacRuby%200.4.zip installed? 

If yes, please open the console.app while you open Pomodori. If you see a stack trace can you paste it here? Thanks

**Comment by redsplat** [comment]
I don't have it installed, doing it now

**Comment by redsplat** [comment]
Hi reborg, installing MacRuby 0.4 did the trick, after that the Pomodori installation worked like a charm. Cheers for the fast response!

Let me know if you are still interested in seeing a stack trace.

**Comment by reborg** [comment]
Good. I'm going to update the documentation on the project main page. It's missing the information about the application dependencies and how to install it. Thanks
