### ISSUE TITLE
Trying to build 0.6, failing.

### ISSUE THREAD

**Issue by nes1983** [reborg/pomodori#8]
Why is there no git submodules file? Apparently,
vendor/hotcocoa-0.5.1+patch is intended to be a submodule, then its
subfolder vendor/hotcocoa-0.5.1+patch/lib/hotcocoa is to be softlinked
to hotcocoa. Hmm. Is the softlink really necessary? Alternatively,
using git subtree (http://github.com/apenwarr/git-subtree) you could
check out only what you need, where you need it.  If I just download
the latest hotcocoa and put it in place, I get this error:

verratnix:pomodori niko$ macrake
(in /Users/niko/repos/pomodori)
Loaded suite test/all_tests
Started
uncaught Objective-C/C++ exception...
2010-10-13 22:38:21.304 macruby[7652:607] An uncaught exception was raised
2010-10-13 22:38:21.306 macruby[7652:607]
/Users/niko/repos/pomodori/vendor/mocha-0.9.5/lib/mocha/mini_test_adapter.rb:26:in
`old_run_method_aliased_by_matchy:': undefined method`name' for
# ChartTest:0x2000d9760 (NoMethodError)

```
   from /Library/Frameworks/MacRuby.framework/Versions/0.7/usr/lib/ruby/1.9.2/minitest/unit.rb:635:in
```

`block'
       from /Library/Frameworks/MacRuby.framework/Versions/0.7/usr/lib/ruby/1.9.2/minitest/unit.rb:633:in
`run_test_suites:'
       from /Library/Frameworks/MacRuby.framework/Versions/0.7/usr/lib/ruby/1.9.2/minitest/unit.rb:576:in
`run:'
2010-10-13 22:38:21.307 macruby[7652:607] *** Terminating app due to
uncaught exception 'NoMethodError', reason:
'/Users/niko/repos/pomodori/vendor/mocha-0.9.5/lib/mocha/mini_test_adapter.rb:26:in
`old_run_method_aliased_by_matchy:': undefined method `name' for
# ChartTest:0x2000d9760 (NoMethodError)

```
   from /Library/Frameworks/MacRuby.framework/Versions/0.7/usr/lib/ruby/1.9.2/minitest/unit.rb:635:in
```

`block'
       from /Library/Frameworks/MacRuby.framework/Versions/0.7/usr/lib/ruby/1.9.2/minitest/unit.rb:633:in
`run_test_suites:'
       from /Library/Frameworks/MacRuby.framework/Versions/0.7/usr/lib/ruby/1.9.2/minitest/unit.rb:576:in
`run:'
'
**\* Call stack at first throw:
(
       0   CoreFoundation                      0x00007fff824a6cc4
__exceptionPreprocess + 180
       1   libobjc.A.dylib                     0x00007fff81ebb0f3
objc_exception_throw + 45
       2   libmacruby.dylib                    0x0000000100162565 rb_vm_raise + 437
       3   libmacruby.dylib                    0x000000010004c849 rb_exc_raise + 9
       4   libmacruby.dylib                    0x0000000100160112
rb_vm_method_missing + 562
       5   libmacruby.dylib                    0x0000000100150bbe
rb_vm_dispatch + 7966
       6   ???                                 0x0000000102d5a5ac 0x0 + 4342523308
       7   ???                                 0x0000000102dc580b 0x0 + 4342962187
       8   libmacruby.dylib                    0x000000010015093e
rb_vm_dispatch + 7326
       9   libmacruby.dylib                    0x00000001001536b0
rb_vm_yield_args + 3040
       10  libmacruby.dylib                    0x000000010014f33f
rb_vm_dispatch + 1695
       11  ???                                 0x0000000102d5a5ac 0x0 + 4342523308
       12  ???                                 0x0000000102da8dc1 0x0 + 4342844865
       13  libmacruby.dylib                    0x0000000100150963
rb_vm_dispatch + 7363
       14  ???                                 0x0000000102d5a5ac 0x0 + 4342523308
       15  ???                                 0x0000000102dc73c4 0x0 + 4342969284
       16  libmacruby.dylib                    0x000000010015093e
rb_vm_dispatch + 7326
       17  ???                                 0x0000000102d5a5ac 0x0 + 4342523308
       18  ???                                 0x0000000116d83187 0x0 + 4678234503
       19  libmacruby.dylib                    0x0000000100153237
rb_vm_yield_args + 1895
       20  libmacruby.dylib                    0x000000010010b6a8 rb_yield + 40
       21  libmacruby.dylib                    0x0000000100021cbd rary_reserve + 861
       22  libmacruby.dylib                    0x000000010015097e
rb_vm_dispatch + 7390
       23  ???                                 0x0000000102d5a5ac 0x0 + 4342523308
       24  ???                                 0x0000000116d8267f 0x0 + 4678231679
       25  libmacruby.dylib                    0x0000000100153237
rb_vm_yield_args + 1895
       26  libmacruby.dylib                    0x000000010010b6a8 rb_yield + 40
       27  libmacruby.dylib                    0x0000000100021cbd rary_reserve + 861
       28  libmacruby.dylib                    0x000000010015097e
rb_vm_dispatch + 7390
       29  ???                                 0x0000000102d5a5ac 0x0 + 4342523308
       30  ???                                 0x0000000116d81e77 0x0 + 4678229623
       31  libmacruby.dylib                    0x0000000100150963
rb_vm_dispatch + 7363
       32  ???                                 0x0000000102d5a5ac 0x0 + 4342523308
       33  ???                                 0x0000000116d7fcf5 0x0 + 4678221045
       34  libmacruby.dylib                    0x0000000100150963
rb_vm_dispatch + 7363
       35  ???                                 0x0000000102d5a5ac 0x0 + 4342523308
       36  ???                                 0x0000000102dc7cf1 0x0 + 4342971633
       37  libmacruby.dylib                    0x0000000100152019
rb_vm_block_eval + 1401
       38  libmacruby.dylib                    0x00000001001609ea rb_rescue2 + 58
       39  libmacruby.dylib                    0x000000010004d080 ruby_finalize + 96
       40  libmacruby.dylib                    0x00000001000ad200 rb_exit + 16
       41  macruby                             0x0000000100000d2f main + 159
       42  macruby                             0x0000000100000c88 start + 52
       43  ???                                 0x0000000000000002 0x0 + 2
)
terminate called after throwing an instance of 'NSException'

**Comment by reborg** [comment]
Hi,
I get this error only if I try with macruby 0.7, which is of course an issue anyway. Just wanted to say that you should be able to compile/build/test just fine with MacRuby 0.6 Can you please double check you're not on 0.7 when you try to test? I'm working on porting Pomodori to Macruby 0.7. Thanks

**Comment by nes1983** [comment]
Can't you just drop whatever version of macruby is required into the repo?

**Comment by reborg** [comment]
I did a few attempts but the macruby installation itself is not self-contained. There are several symbolic links to other parts of the system where the macruby installer copied files or directory and I can't break those dependencies. What I can do is including the MacRuby 0.6.pkg installed in the repo, but it still requires you to execute the installation. At that point I think it's the same as pointing you to the macruby installation from the Pomodori homepage. Sorry, you need to install the correct MacRuby version (as a developer) while if you just want to run it the runtime it's embedded in the distributable Pomodori.zip.
